### ISSUE TITLE
GNAF-2016-05 contains 2018 data

### ISSUE THREAD

**Issue by nicholascar** [AGLDWG/gnaf-dataset#36] opened 2019-02-09 11:37 UTC
See the Date Last Modified on http://gnafld.net/2016-05/address/GAACT714845933

**Comment by ashleysommer** [comment] 2019-02-11 01:00
Nick, something really odd going on here.
See the canonical instance uri on bottom of the page, it is a gnaf-current URI. The 2016 version should be showing gnaf/2016-05 uris.
Also, check out the home page, at http://gnafld.net/2016-05/
It is rendering the gnaf-current home page. The home template for gnaf2016-05 has in its template:
<h1>G-NAF May, 2016<br />Distributed as Linked Data</h1>

**Comment by ashleysommer** [comment] 2019-02-11 01:01
Did somebody change the apache config and redirect /2016-05/ to the pyldapi code for gnaf-current?

**Comment by ashleysommer** [comment] 2019-02-11 01:19
It was an error in gnaf2016ldapi app.wsgi, caused by a bad git merge last week. It had caused the gnaf2016ldapi app to use config, models, and templates from the gnaf-current ldapi app.

Fixed now.

**Closed by ashleysommer** 2019-02-11 01:19 UTC
Labels: priority-1
